### ISSUE TITLE
OP6: Icon has black background.

### ISSUE THREAD

**Issue by Not-James-Bond** [sameerasw/folder-icons#1]
OP6 icon have black background even in .ico. 
![image](https://user-images.githubusercontent.com/32868290/201718837-d8218078-40aa-4f7f-858b-375e56002902.png)

**Comment by sameerasw** [comment]
> OP6 icon have black background even in .ico. ![image](https://user-images.githubusercontent.com/32868290/201718837-d8218078-40aa-4f7f-858b-375e56002902.png)

Oops... I fixed this a while before but think added the old icon again...  will be updated soon :)

**Comment by Not-James-Bond** [comment]
@sameerasw It again have black background in v2.4

**Comment by sameerasw** [comment]
> @sameerasw It again have black background in v2.4

thnks for reminding... :)

 I fixed it twice at this point but I somehow keep adding it back... give me few mins... I'm gonna find every op6 icon with background and burn them, so it won't come bac ...lol

**Comment by sameerasw** [comment]
> > @sameerasw It again have black background in v2.4
> 
> thnks for reminding... :)
> 
> I fixed it twice at this point but I somehow keep adding it back... give me few mins... I'm gonna find every op6 icon with background and burn them, so it won't come bac ...lol

{Done](https://github.com/sameerasw/folder-icons/tree/v2.5)
