### ISSUE TITLE
Add Emulator icons, and anothers.

### ISSUE THREAD

**Issue by ionuttbara** [sameerasw/folder-icons#10]
I have RetroArch installed. I want to organize my ROMs by consoles. This is request for adding an folder icon of configurations (any configurations), folder icons for consoles (sega genesis, CD, saturn, dreamcast, nintendo switch, 3ds, wii, snes, nes and sony playstation 1,2,3) and a drive icon which can be indicate emulator content.

**Comment by sameerasw** [comment]
Added in 13be704 and in [release v3.1](https://github.com/sameerasw/folder-icons/releases/tag/v3.1)

Re-open for missing requests :)
