### ISSUE TITLE
[suggestion] backup drive

### ISSUE THREAD

**Issue by JustRed23** [sameerasw/folder-icons#13]
Would be nice to have a backup drive icon, something like the [backup folder icon](https://raw.githubusercontent.com/sameerasw/folder-icons/main/ICO/backups.ico)

**Comment by sameerasw** [comment]
Added in 12a9819 :)

https://github.com/sameerasw/folder-icons/blob/12a98195ab37931d9ca859243e2e1da746a21f22/ICO/drive_icons/drive-backups.ico
https://github.com/sameerasw/folder-icons/blob/12a98195ab37931d9ca859243e2e1da746a21f22/PNGs/drive-backups.png

**Comment by JustRed23** [comment]
> Added in [12a9819](https://github.com/sameerasw/folder-icons/commit/12a98195ab37931d9ca859243e2e1da746a21f22) :)
> 
> https://github.com/sameerasw/folder-icons/blob/12a98195ab37931d9ca859243e2e1da746a21f22/ICO/drive_icons/drive-backups.ico https://github.com/sameerasw/folder-icons/blob/12a98195ab37931d9ca859243e2e1da746a21f22/PNGs/drive-backups.png

Thx :)
