### ISSUE TITLE
Emulator Icons

### ISSUE THREAD

**Issue by JuanPabloPearce** [sameerasw/folder-icons#19]
Would it be possible to add icons for the following emulators?

Citra
Yuzu
Ryujinx
RPCS3
MelonDS
Cemu
Clone Hero
Dolphin
mGBA
PPSSPP (standard and Gold)
Rosalie's Mupen GUI (n64)
Vita3K

I am making a games database, and I only seem to find less than ideal folder style ICO files for these.

**Comment by sameerasw** [comment]
> Would it be possible to add icons for the following emulators?
> 
> Citra Yuzu Ryujinx RPCS3 MelonDS Cemu Clone Hero Dolphin mGBA PPSSPP (standard and Gold) Rosalie's Mupen GUI (n64) Vita3K
> 
> I am making a games database, and I only seem to find less than ideal folder style ICO files for these.

Sure, I'll add prolly tonight :)

**Comment by sameerasw** [comment]
Whelp, 'tonight' became next week.. sorry about the delay. :)

Added in b945aba
