### ISSUE TITLE
An icon for work

### ISSUE THREAD

**Issue by SangeethSujith** [sameerasw/folder-icons#2]
A briefcase image

**Comment by sameerasw** [comment]
> A briefcase image

Making now... will be in tomorrow's release :)

**Comment by SangeethSujith** [comment]
An icon for tools will be also great

**Comment by sameerasw** [comment]
> An icon for tools will be also great

sure
like with a gear icon?

**Comment by sameerasw** [comment]
> > An icon for tools will be also great
> 
> sure like with a gear icon?

![image](https://user-images.githubusercontent.com/68902530/201729516-80b90b27-2a80-4ac0-92c7-6ecf10cff81c.png)
