### ISSUE TITLE
DataBase, Markdown, JSON, php, SASS, VUE

### ISSUE THREAD

**Issue by TIMEELAPSE-CN** [sameerasw/folder-icons#23]
**Please provide a 500x500 or better image if possible**
Database
![DataBase](https://github.com/sameerasw/folder-icons/assets/118769938/33863101-cfc3-4d67-857e-53b348ab1da0)
Markdown
![Markdown](https://github.com/sameerasw/folder-icons/assets/118769938/39ce60fb-c48a-4590-8734-3a31d7a1a104)
JSON
![JSON](https://github.com/sameerasw/folder-icons/assets/118769938/fe895a28-57dc-4579-84a9-62f61c639cb7)
php
![php](https://github.com/sameerasw/folder-icons/assets/118769938/17dc229d-5136-4571-8007-96e27725e481)
SASS
![SASS](https://github.com/sameerasw/folder-icons/assets/118769938/e850c286-9e41-414e-ad14-e4ca5c393dc2)
vue
![vue](https://github.com/sameerasw/folder-icons/assets/118769938/2d5d4182-5dcc-4569-9c3b-f6cb3c0d3817)

**Comment by sameerasw** [comment]
I don't use Windows anymore so I can't create .ico files... but you can use my web app to create icons with simple colors which will output 1000x1000 as I remember but PNGs.
https://folder-studio.netlify.app/

I'll add 500x500 PNGs :)

**Comment by TIMEELAPSE-CN** [comment]
OK, thanks.> I don't use Windows anymore so I can't create .ico files... but you can use my web app to create icons with simple colors which will output 1000x1000 as I remember but PNGs.
> 
> https://folder-studio.netlify.app/
> 
> 
> 
> I'll add 500x500 PNGs :)

**Comment by sameerasw** [comment]
Added in 63528fe !

You can grab them from [folder-icons](https://sameerasw.github.io/icons/windows.html) or from the last commit. <3
