### ISSUE TITLE
Red Hat Folder

### ISSUE THREAD

**Issue by jwoodard80** [sameerasw/folder-icons#24]
We have RHEL servers at my work. I'd love to have a folder for them. If you have made a tutorial or something I did not see it. 

Thank you for any consideration in this. :-)

![redhat-icon-svgrepo-com](https://github.com/sameerasw/folder-icons/assets/10240627/f173c5d7-d17a-40c4-8c4e-85bc4bc78b15)
**Please provide a 500x500 or better image if possible**

**Comment by sameerasw** [comment]
Added in 704afac (this link will give you the new added icons). Yes, you can make one yourself with the source .psd (Photoshop) file or with the [webapp](https://folder-studio.netlify.app/) I made but the web app is limited.

But, glad to help <3

**Comment by jwoodard80** [comment]
Holy crap dude! Thank you!! Much appreciate the amazing turn around time. :-)
