### ISSUE TITLE
Curseforge Icon

### ISSUE THREAD

**Issue by iglee42** [sameerasw/folder-icons#27]
Can you add please a curseforge folder icon ?
![egs-curseforge-overwolf-ic1-400x400-efe6f7172cef](https://github.com/sameerasw/folder-icons/assets/50081542/3476712d-3847-47a6-b5a2-a0682fd7276d)

**Comment by sameerasw** [comment]
@iglee42 Added in f20ec2a :)

**Comment by iglee42** [comment]
Thanks
