### ISSUE TITLE
ICO/halo.png

### ISSUE THREAD

**Issue by FadeMind** [sameerasw/folder-icons#29]
https://github.com/sameerasw/folder-icons/blob/main/ICO/halo.png
Hmmm
![20240814-1723618272](https://github.com/user-attachments/assets/9d7e2366-538f-4959-9be7-63917f83eff1)
One file was not converted? :>

**Comment by sameerasw** [comment]
Maybe I'll try to add some new and these missing icons tonight.... :)

I couldn't merge your pull since it removed the PNG. so if youc an, please keep both files in so I will merge it and add indexes for the website <3
