### ISSUE TITLE
More browser icons

### ISSUE THREAD

**Issue by l3xrom** [sameerasw/folder-icons#3]
Please add [CentBrowser](https://www.centbrowser.com/) and [SRWare Iron](https://www.srware.net/iron/) folder icons.

**Comment by sameerasw** [comment]
> Please add [CentBrowser](https://www.centbrowser.com/) and [SRWare Iron](https://www.srware.net/iron/) folder icons.

sure... will be added in next release.. Also you can get them before the release from the telegram chat group when available :)
[TIDWIB Telegram](https://t.me/tidwib)

**Comment by sameerasw** [comment]
> Please add [CentBrowser](https://www.centbrowser.com/) and [SRWare Iron](https://www.srware.net/iron/) folder icons.

They are ready... You can get from [here](https://t.me/tidwib/510) or wait for main releases :)
![image](https://user-images.githubusercontent.com/68902530/202699571-afc27a4e-81aa-4383-8772-0bb534af992c.png)

**Comment by l3xrom** [comment]
Fantastic fast and good! Thanks!
