### ISSUE TITLE
Website link in README leads to 404

### ISSUE THREAD

**Issue by ArgonGlow** [sameerasw/folder-icons#32]
Just wanted to give you a heads up that the website link in the README is no longer valid (404). I did find what I needed through the 'About' section, but someone else might not.

https://github.com/sameerasw/folder-icons/blob/34d31f2538f34638bb6ee09472f808737bfd4ed0/README.md?plain=1#L4

**Comment by sameerasw** [comment]
> Just wanted to give you a heads up that the website link in the README is no longer valid (404). I did find what I needed through the 'About' section, but someone else might not.
> 
> https://github.com/sameerasw/folder-icons/blob/34d31f2538f34638bb6ee09472f808737bfd4ed0/README.md?plain=1#L4

Thanks for pointing out! I forgot to update it since I moved the page to my website.
Fixed in 81f1f52
