### ISSUE TITLE
Vagrant folder icon

### ISSUE THREAD

**Issue by eggbean** [sameerasw/folder-icons#33]
Could you please add a folder icon for Hashicorp Vagrant?

https://e7.pngegg.com/pngimages/339/633/png-clipart-vagrant-logo-hashicorp-graphics-brand-vagrant-blue-angle.png

I've asked for a couple of icons before and they've been great. Thanks.

**Comment by sameerasw** [comment]
Added in bd76b9e

**Comment by eggbean** [comment]
Excellent. Looks good, thanks!
