### ISSUE TITLE
EA & GOG Galaxy

### ISSUE THREAD

**Issue by ToxicJellyTV** [sameerasw/folder-icons#34]
Please make an Electronic Arts (EA) and a GOG Galaxy folder icon for the respective games libraries.

![image](https://github.com/user-attachments/assets/f86dc401-fab7-4e18-bf6c-553cde5d45b8)
![image](https://github.com/user-attachments/assets/4c21348a-521f-45fa-a47f-a1141394efa8)
![image](https://github.com/user-attachments/assets/fd97850f-43fc-422f-9fd0-c6a3eeddc23b)

**Comment by sameerasw** [comment]
Added in 4f54c7d :)
EA icon will be unlocked for 39.99USD 😅
