### ISSUE TITLE
Golang folder icon

### ISSUE THREAD

**Issue by eggbean** [sameerasw/folder-icons#35]
Please make a Golang folder icon. There is also the gopher icon for Golang, but I personally don't like that goofy gopher. I think a very light grey background will be best for this logo. Thank you!

https://w7.pngwing.com/pngs/566/160/png-transparent-golang-hd-logo.png

**Comment by sameerasw** [comment]
Added both icons in 4f54c7d :)

**Comment by eggbean** [comment]
Thank you!
