### ISSUE TITLE
Icons slightly offcenter

### ISSUE THREAD

**Issue by jwols27** [sameerasw/folder-icons#37]
Icons seem slightly offcenter when the folder view option is set as "Medium Icons", "Large Icons", or "Extra Large Icons".

In the attached image, the left folder uses the "graphics" icon and the right folder is uses the default Windows 11 folder icon. This seems to affect all of the folder icons.
It might affect the driver icons too, but I didn't notice anything at first glance so whatever.
![image](https://github.com/user-attachments/assets/4632e24a-768d-47a7-8cb2-a271986a2622)

**Comment by sameerasw** [comment]
Ohhh I see that, I think the shadow layer is causing some alignment issues in photoshop. I will try to fix it in the template photoshop file soon. But might not be able to update the existing icons tho ;)

Thanks for pointing out!
