### ISSUE TITLE
CopyQ and VHD folders

### ISSUE THREAD

**Issue by eggbean** [sameerasw/folder-icons#5]
Hi. Could I request a couple of icons? One is a CopyQ folder icon with the CopyQ logo:

![image](https://github.com/sameerasw/folder-icons/assets/815311/db18802a-2b79-4df8-87f0-22086c4348b6)

The other is a folder icon for VHD virtual disk files, which would basically be a folder icon with a disk icon on it.

**Comment by eggbean** [comment]
I also made an icon for Vim config files (vimfiles folder) but I couldn't get it right using Adobe Illustrator, so someone fixed it. If you could add this .svg file to your icon set, that would be great.

https://user-images.githubusercontent.com/73294041/230039398-b5174596-1b69-4b9b-950b-281f58bbdfa8.svg

**Comment by sameerasw** [comment]
> I also made an icon for Vim config files (vimfiles folder) but I couldn't get it right using Adobe Illustrator, so someone fixed it. If you could add this .svg file to your icon set, that would be great.
> 
> https://user-images.githubusercontent.com/73294041/230039398-b5174596-1b69-4b9b-950b-281f58bbdfa8.svg
> 
> (It doesn't seem to display correctly in Chrome)

![image](https://github.com/sameerasw/folder-icons/assets/68902530/7d9c363d-16b9-453d-9e26-a13a352cf891)

Think it's coz there's a linked media inside it... I'll make a vim folder separately :)

**Comment by sameerasw** [comment]
Added in v2.7 
https://github.com/sameerasw/folder-icons/tree/v2.7

**Comment by eggbean** [comment]
Hey, thanks for the vhd and copyq icons. I cannot find the vimfiles one though? Cheers.

**Comment by sameerasw** [comment]
> Hey, thanks for the vhd and copyq icons. I cannot find the vimfiles one though? Cheers.

Sorry I missed it... added it too :)
https://github.com/sameerasw/folder-icons/tree/v2.7

**Comment by eggbean** [comment]
Thanks!
