### ISSUE TITLE
Data drive icon

### ISSUE THREAD

**Issue by Mimexe** [sameerasw/folder-icons#8]
For D: drive for example

**Comment by sameerasw** [comment]
> For D: drive for example
Hi!
I didn't get the idea... So, A drive icon for storing data? Like a database drive?

**Comment by ionuttbara** [comment]
something like that

**Comment by Mimexe** [comment]
> > For D: drive for example
> 
> Hi! I didn't get the idea... So, A drive icon for storing data? Like a database drive?

Ok, thats maybe a dumb idea I have requested this because I have a folder named Data is for... storing data like my coding projects or images and the root of D drive I have games, softwares etc. So a folder icon maybe it's good for me. But yeah sorry for wasting your time it's a bad idea
