### ISSUE TITLE
Game Icons

### ISSUE THREAD

**Issue by gk98s** [sameerasw/folder-icons#9]
it would be really cool if you would add folder icons for some popular games such as(just examples): Stardew Valley, CS:GO, Valorant, Minecraft, PUBG, Fortnite, Grounded, The Escapists 2, Hearts Of Iron 4, EU4, Cities Skylines etc. Though it might be a lot of work since those are just a few games and there are SO MANY out there.

**Comment by sameerasw** [comment]
Added in 71f7647 with [Release v3.0](https://github.com/sameerasw/folder-icons/releases/tag/v3.0)

![image](https://github.com/sameerasw/folder-icons/assets/68902530/11a8de6c-2eb3-4a18-9a24-31bc30db069a)
